#!/usr/bin/env python3
# Generated from protocols/method-registry.yaml by scripts/generate_method_capabilities.py.
# Do not edit this file directly.

METHOD_CAPABILITIES = {
    'projection.start': 'projection.start',
    'system.health': 'system.health.read',
    'system.shutdown': 'system.shutdown',
    'event.subscribe': 'event.subscribe',
    'projection.render': 'projection.render',
    'projection.layers.submit': 'projection.render',
    'projection.output.clear': 'projection.control',
    'projection.output.frame': 'projection.output.read',
    'projection.session.command': 'projection.control',
    'spatial_ui.status': 'spatial_ui.read',
    'spatial_ui.components': 'spatial_ui.read',
    'spatial_ui.windows': 'spatial_ui.read',
    'spatial_ui.focus.status': 'spatial_ui.read',
    'spatial_ui.layout.status': 'spatial_ui.read',
    'spatial_ui.metrics': 'spatial_ui.read',
    'spatial_ui.component.create': 'spatial_ui.write',
    'spatial_ui.task.create': 'spatial_ui.write',
    'spatial_ui.task.update': 'spatial_ui.write',
    'spatial_ui.component.update': 'spatial_ui.write',
    'spatial_ui.component.remove': 'spatial_ui.write',
    'spatial_ui.window.open': 'spatial_ui.write',
    'spatial_ui.window.move': 'spatial_ui.input',
    'spatial_ui.window.resize': 'spatial_ui.input',
    'spatial_ui.window.hide': 'spatial_ui.write',
    'spatial_ui.window.show': 'spatial_ui.write',
    'spatial_ui.window.target': 'spatial_ui.write',
    'spatial_ui.window.restore': 'spatial_ui.write',
    'spatial_ui.window.close': 'spatial_ui.write',
    'spatial_ui.layout.apply': 'spatial_ui.write',
    'spatial_ui.layout.reset': 'spatial_ui.write',
    'spatial_ui.input': 'spatial_ui.input',
    'spatial_ui.interaction.cancel': 'spatial_ui.input',
    'spatial_ui.focus': 'spatial_ui.input',
    'spatial_ui.notification.create': 'spatial_ui.write',
    'spatial_ui.notification.clear': 'spatial_ui.write',
    'spatial_ui.state.save': 'spatial_ui.write',
    'spatial_ui.state.load': 'spatial_ui.read',
    'spatial_ui.target.lost': 'spatial_ui.system',
    'spatial_ui.target.available': 'spatial_ui.system',
    'spatial_ui.reset': 'spatial_ui.write',
    'spatial.health': 'spatial.read',
    'spatial.state': 'spatial.read',
    'spatial.source.start': 'spatial.control',
    'spatial.source.stop': 'spatial.control',
    'spatial.detect': 'spatial.control',
    'spatial.select': 'spatial.control',
    'spatial.calibrate': 'spatial.control',
    'spatial.observer.set': 'spatial.observer.write',
    'spatial.reset': 'spatial.control',
}


def capability_for_method(method: str) -> str:
    try:
        return METHOD_CAPABILITIES[method]
    except KeyError as error:
        raise ValueError(f"method has no capability mapping: {method}") from error
