#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from method_capabilities import method_capabilities


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--python-output", type=Path)
    args = parser.parse_args()
    capabilities = method_capabilities()
    lines = [
        "#pragma once",
        "",
        "// Generated from protocols/method-registry.yaml by scripts/generate_method_capabilities.py.",
        "// Do not edit this file directly.",
        "",
        "#include <QString>",
        "",
        "namespace astra::common::generated {",
        "",
        "inline QString methodCapability(const QString &method)",
        "{",
    ]
    for method, capability in capabilities.items():
        lines.append(
            f"    if (method == QStringLiteral({json.dumps(method)})) "
            f"return QStringLiteral({json.dumps(capability)});"
        )
    lines.extend(["    return {};", "}", "", "} // namespace astra::common::generated", ""])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    if args.python_output:
        python_lines = [
            "#!/usr/bin/env python3",
            "# Generated from protocols/method-registry.yaml by scripts/generate_method_capabilities.py.",
            "# Do not edit this file directly.",
            "",
            "METHOD_CAPABILITIES = {",
        ]
        for method, capability in capabilities.items():
            python_lines.append(f"    {method!r}: {capability!r},")
        python_lines.extend(
            [
                "}",
                "",
                "",
                "def capability_for_method(method: str) -> str:",
                "    try:",
                "        return METHOD_CAPABILITIES[method]",
                "    except KeyError as error:",
                '        raise ValueError(f"method has no capability mapping: {method}") from error',
                "",
            ]
        )
        args.python_output.parent.mkdir(parents=True, exist_ok=True)
        args.python_output.write_text("\n".join(python_lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
