#pragma once

// Generated from protocols/method-registry.yaml by scripts/generate_method_capabilities.py.
// Do not edit this file directly.

#include <QString>

namespace astra::common::generated {

inline QString methodCapability(const QString &method)
{
    if (method == QStringLiteral("projection.start")) return QStringLiteral("projection.start");
    if (method == QStringLiteral("system.health")) return QStringLiteral("system.health.read");
    if (method == QStringLiteral("system.shutdown")) return QStringLiteral("system.shutdown");
    if (method == QStringLiteral("event.subscribe")) return QStringLiteral("event.subscribe");
    if (method == QStringLiteral("projection.render")) return QStringLiteral("projection.render");
    if (method == QStringLiteral("projection.layers.submit")) return QStringLiteral("projection.render");
    if (method == QStringLiteral("projection.output.clear")) return QStringLiteral("projection.control");
    if (method == QStringLiteral("projection.output.frame")) return QStringLiteral("projection.output.read");
    if (method == QStringLiteral("projection.session.command")) return QStringLiteral("projection.control");
    if (method == QStringLiteral("spatial_ui.status")) return QStringLiteral("spatial_ui.read");
    if (method == QStringLiteral("spatial_ui.components")) return QStringLiteral("spatial_ui.read");
    if (method == QStringLiteral("spatial_ui.windows")) return QStringLiteral("spatial_ui.read");
    if (method == QStringLiteral("spatial_ui.focus.status")) return QStringLiteral("spatial_ui.read");
    if (method == QStringLiteral("spatial_ui.layout.status")) return QStringLiteral("spatial_ui.read");
    if (method == QStringLiteral("spatial_ui.metrics")) return QStringLiteral("spatial_ui.read");
    if (method == QStringLiteral("spatial_ui.component.create")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.task.create")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.task.update")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.component.update")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.component.remove")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.window.open")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.window.move")) return QStringLiteral("spatial_ui.input");
    if (method == QStringLiteral("spatial_ui.window.resize")) return QStringLiteral("spatial_ui.input");
    if (method == QStringLiteral("spatial_ui.window.hide")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.window.show")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.window.target")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.window.restore")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.window.close")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.layout.apply")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.layout.reset")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.input")) return QStringLiteral("spatial_ui.input");
    if (method == QStringLiteral("spatial_ui.interaction.cancel")) return QStringLiteral("spatial_ui.input");
    if (method == QStringLiteral("spatial_ui.focus")) return QStringLiteral("spatial_ui.input");
    if (method == QStringLiteral("spatial_ui.notification.create")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.notification.clear")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.state.save")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial_ui.state.load")) return QStringLiteral("spatial_ui.read");
    if (method == QStringLiteral("spatial_ui.target.lost")) return QStringLiteral("spatial_ui.system");
    if (method == QStringLiteral("spatial_ui.target.available")) return QStringLiteral("spatial_ui.system");
    if (method == QStringLiteral("spatial_ui.reset")) return QStringLiteral("spatial_ui.write");
    if (method == QStringLiteral("spatial.health")) return QStringLiteral("spatial.read");
    if (method == QStringLiteral("spatial.state")) return QStringLiteral("spatial.read");
    if (method == QStringLiteral("spatial.source.start")) return QStringLiteral("spatial.control");
    if (method == QStringLiteral("spatial.source.stop")) return QStringLiteral("spatial.control");
    if (method == QStringLiteral("spatial.detect")) return QStringLiteral("spatial.control");
    if (method == QStringLiteral("spatial.select")) return QStringLiteral("spatial.control");
    if (method == QStringLiteral("spatial.calibrate")) return QStringLiteral("spatial.control");
    if (method == QStringLiteral("spatial.observer.set")) return QStringLiteral("spatial.observer.write");
    if (method == QStringLiteral("spatial.reset")) return QStringLiteral("spatial.control");
    return {};
}

} // namespace astra::common::generated
